### ISSUE TITLE
Old broken sarif schema URL being used

### ISSUE THREAD

**Issue by midwestKC-coder** [SvanBoxel/zaproxy-to-ghas#39]
Action uses schema (  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",) which is currently a broken URL.  It is a known issue.  See bullet #5 (https://github.com/oasis-tcs/sarif-spec/issues/509).  GitHub for CodeQL has switched to a different URL ("$schema" : "https://json.schemastore.org/sarif-2.1.0.json").  Current schema still imports correctly into GitHub since it supports new and old URL.  It does prevent loading into such tools as sarif vewer extension for VS Code.  Plan to sumbit a PR to use the same URL as codeQL.

**Comment by SvanBoxel** [comment]
Closed by https://github.com/SvanBoxel/zaproxy-to-ghas/pull/40
